BIND_PATH:           /sdf
CONTAINER_WCSIM:     /sdf/home/j/junjie/sdf-data/sif/cider-dataprod_24.09.25.sif
CONTAINER_WCPROD:    /sdf/home/j/junjie/sdf-data/sif/cider-dataprod_24.09.25.sif
WCPROD_DB_FILE:      /sdf/home/j/junjie/SIREN/WCProd/wcprod_cider/example_wcte_vox_20000.db
REBIN_DB_FILE:       /sdf/home/j/junjie/SIREN/CIDeR_DT/CIDeR_DT/test_rebin.db
WCPROD_PROJECT:      example_wcte_vox_20000
WCPROD_NEVENTS:      20000
WCPROD_NPHOTONS:     1
WCPROD_NLOOPS:       1
WCPROD_STORAGE_ROOT: /sdf/home/j/junjie/sdf-data/voxel/playground/test_sub
WCPROD_WORK_DIR:     /sdf/home/j/junjie/sdf-data/voxel/playground/test_sub
SLURM_LOG_DIR: /sdf/home/j/junjie/sdf-data/voxel/playground/test_sub/slurm_log
SLURM_TIME:    1:00:00
SLURM_MEM:     4
SLURM_NCPU:    1
SLURM_NJOBS_TOTAL: 1
SLURM_NJOBS_CONCURRENT: 1
SLURM_ACCOUNT: neutrino
SLURM_PARTITION: milano
SLURM_PREEMPTABLE: True
SLURM_NODELIST: ''
WCSIM_HOME: /src/WCSim
WC_RMAX: 1271.96
WC_ZMAX: 1379.118
REBIN_GAP_SPACE: 100
REBIN_GAP_ANGLE: 15
REBIN_N_BINS_PHI0: 4
NUM_SHARDS: 100