BIND_PATH:           /sdf
CONTAINER_WCSIM:     /sdf/home/j/junjie/sdf-data/sif/wcsim-plus_wcsim.24.08.25.sif
CONTAINER_WCPROD:    /sdf/home/j/junjie/sdf-data/sif/wcprod_24.08.25.sif
WCPROD_DB_FILE:      /sdf/home/j/junjie/SIREN/WCProd/wcprod_cider/example_vox_10000.db
WCPROD_PROJECT:      example_project_vox_10000
WCPROD_NEVENTS:      10000
WCPROD_NPHOTONS:     1
WCPROD_NLOOPS:       1
WCPROD_STORAGE_ROOT: /sdf/home/j/junjie/sdf-data/voxel/v000
WCPROD_WORK_DIR:     /sdf/home/j/junjie/sdf-data/voxel/v000
SLURM_LOG_DIR: /sdf/home/j/junjie/sdf-data/voxel/v000/slurm_log
SLURM_TIME:    0:30:00
SLURM_MEM:     4
SLURM_NCPU:    1
SLURM_NJOBS_TOTAL: 2
SLURM_NJOBS_CONCURRENT: 1
SLURM_ACCOUNT: neutrino
SLURM_PARTITION: milano
SLURM_PREEMPTABLE: True
SLURM_NODELIST: ''
WCSIM_HOME: /src/WCSim